M48
; DRILL file {KiCad 8.0.0} date 2024-03-27T13:59:55-0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-27T13:59:55-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.023Y-2.3087
X4.214Y-2.3087
T2
X4.0112Y-2.1894
X4.2258Y-2.1894
M30
